scan_filter_chain:
- name: shadows0
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 0
    max_angle: 90
    neighbors: 20
    window: 1
# - name: shadows1
#   type: laser_filters/ScanShadowsFilter
#   params:
#     min_angle: 100
#     max_angle: 280
#     neighbors: 20
#     window: 1